### ISSUE TITLE
ImportError: No module named 'gammu._gammu'

### ISSUE THREAD

**Issue by abadger1406** [gammu/python-gammu#21]
Still struggling to get python-gammu working on Ubuntu , have install 1.38.4 latest gammu and 2.9 latest python-gammu bundings, the error I see is:-

```
(ve) dave@crowthorne:~/Downloads/python-gammu-2.9$ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gammu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/Downloads/python-gammu-2.9/gammu/__init__.py", line 26, in <module>
    from gammu._gammu import *
ImportError: No module named 'gammu._gammu'
>>> 
```

```(ve) dave@crowthorne:~/Downloads/python-gammu-2.9$ lsb_release -a
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:printing-9.20160110ubuntu5-amd64:printing-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty(ve) dave@crowthorne:~/Downloads/gammu-1.38.4$ sudo make install
make -C build-configure install
make[1]: Entering directory '/home/dave/Downloads/gammu-1.38.4/build-configure'
make[2]: Entering directory '/home/dave/Downloads/gammu-1.38.4/build-configure'
make[3]: Entering directory '/home/dave/Downloads/gammu-1.38.4/build-configure'
...
...
-- Up-to-date: /usr/share/bash-completion/completions/gammu
-- Up-to-date: /lib/systemd/system/gammu-smsd.service
make[1]: Leaving directory '/home/dave/Downloads/gammu-1.38.4/build-configure'
(ve) dave@crowthorne:~/Downloads/gammu-1.38.4$ 

(ve) dave@crowthorne:~/Downloads/python-gammu-2.9$ python setup.py install
running install
running bdist_egg
running egg_info
writing python_gammu.egg-info/PKG-INFO
writing top-level names to python_gammu.egg-info/top_level.txt
writing dependency_links to python_gammu.egg-info/dependency_links.txt
reading manifest file 'python_gammu.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_gammu.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/_gammu.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/__init__.py -> build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/data.py -> build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/worker.py -> build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/smsd.py -> build/bdist.linux-x86_64/egg/gammu
copying build/lib.linux-x86_64-3.5/gammu/exception.py -> build/bdist.linux-x86_64/egg/gammu
byte-compiling build/bdist.linux-x86_64/egg/gammu/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gammu/data.py to data.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gammu/worker.py to worker.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gammu/smsd.py to smsd.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gammu/exception.py to exception.cpython-35.pyc
creating stub loader for gammu/_gammu.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/gammu/_gammu.py to _gammu.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying python_gammu.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_gammu.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_gammu.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_gammu.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
gammu.__pycache__._gammu.cpython-35: module references __file__
creating dist
creating 'dist/python_gammu-2.9-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing python_gammu-2.9-py3.5-linux-x86_64.egg
creating /home/dave/Env/ve/lib/python3.5/site-packages/python_gammu-2.9-py3.5-linux-x86_64.egg
Extracting python_gammu-2.9-py3.5-linux-x86_64.egg to /home/dave/Env/ve/lib/python3.5/site-packages
Adding python-gammu 2.9 to easy-install.pth file

Installed /home/dave/Env/ve/lib/python3.5/site-packages/python_gammu-2.9-py3.5-linux-x86_64.egg
Processing dependencies for python-gammu==2.9
Finished processing dependencies for python-gammu==2.9
(ve) dave@crowthorne:~/Downloads/python-gammu-2.9$ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gammu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dave/Downloads/python-gammu-2.9/gammu/__init__.py", line 26, in <module>
    from gammu._gammu import *
ImportError: No module named 'gammu._gammu'
>>> 
```

**Comment by abadger1406** [comment]
Now it is working, can only assume I ```
dave     29762 29653  0 Jun25 ?        00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell chrome-extension://gphhapmejobijbbhgpjhcjognlahblep/
(ve) dave@crowthorne:/home/ve/scripts/texts$ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gammu
>>> quit()
(ve) dave@crowthorne:/home/ve/scripts/texts$ 
```


```
(ve) dave@crowthorne:/home/ve/scripts/texts$ sudo apt-get install libgammu-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libgammu-dev : Depends: libgammu8 (= 1.38.1-1) but 1.38.1-1+deb.cihar.com~yakkety.1 is to be installed
                Depends: libgsmsd8 (= 1.38.1-1) but 1.38.1-1+deb.cihar.com~yakkety.1 is to be installed
E: Unable to correct problems, you have held broken packages.
(ve) dave@crowthorne:/home/ve/scripts/texts$ 


```

**Comment by codenoid** [comment]
pls reopen, i got same error
