### ISSUE TITLE
ERROR: test_emoji_folder (test.test_dummy.BasicDummyTest)

### ISSUE THREAD

**Issue by sergiomb2** [gammu/python-gammu#23]
Hi, 
```
======================================================================
ERROR: test_emoji_folder (test.test_dummy.BasicDummyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-gammu-2.9/test/test_dummy.py", line 377, in test_emoji_folder
    os.path.exists(os.path.join(self.dummy_dir, 'fs', name))
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f618' in position 35: ordinal not in range(128)
----------------------------------------------------------------------
Ran 50 tests in 32.334s
FAILED (errors=1)
```

full logs here : https://koji.fedoraproject.org/koji/taskinfo?taskID=21340990 
what this may be ? have you any idea ? 
In a new build I checked and the test failure is just in python2
Thanks

**Comment by nijel** [comment]
Maybe the tests are not executed using unicode locale?
