### ISSUE TITLE
How to get USSD response?

### ISSUE THREAD

**Issue by agn-7** [gammu/python-gammu#34]
How to send a USSD code (`*140*11#`) and get its response?

Here is what I have done so far:

```
import gammu
import unittest


class USSD(unittest.TestCase):
    test_dir = None
    config_name = '/code/config_files/config-smsd.ini'
    dummy_dir = None
    _called = False
    _state_machine = None

    def get_statemachine(self):
        state_machine = gammu.StateMachine()
        state_machine.ReadConfig(Filename=self.config_name)
        state_machine.Init()
        self._state_machine = state_machine
        return state_machine

    def ussd_callback(self, state_machine, response, data):
        """
        Callback on USSD data.
        """
        self._called = True
        self.assertEqual(response, 'USSD')
        self.assertEqual(data['Text'], 'Reply for charge rate')
        self.assertEqual(data['Status'], 'NoActionNeeded')

    def test_ussd(self):
        self._called = False
        state_machine = self.get_statemachine()
        state_machine.SetIncomingCallback(self.ussd_callback)
        state_machine.SetIncomingUSSD()
        state_machine.DialService('*140*11#')
        self.assertTrue(self._called)


if __name__ == '__main__':
    try:
        USSD().test_ussd()
    except KeyboardInterrupt:
        import sys
        sys.exit(0)
```

Out:

```
Traceback (most recent call last):
  File "ussd_2.py", line 42, in <module>
    ussd.test_ussd()
  File "ussd_2.py", line 36, in test_ussd
    self.assertTrue(self._called)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

**Comment by nijel** [comment]
You need an event loop as well to handle device communication. Example is at https://github.com/gammu/python-gammu/blob/master/examples/service_numbers.py
